version: '3'
services:
  db:
    image: mysql:5.6.47
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=match_hike_development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/application
    links:
      - db
